name: License Tests
on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to use'
        type: string
        default: 'ubuntu-latest'
      branch:
        description: 'Branch to check out'
        type: string
        default: ${{ github.ref }}
      action_branch:
        description: 'Branch to check out'
        type: string
        default: main
      custom_labels:
        description: 'Custom labels to use'
        type: string
        default: '{}'
      pr_number:
        description: 'Optional pull request number'
        type: string
        default: ''
      error_on_failure:
        description: 'Throws an error if the title not adheres to Conventional Commit format or testing phase is ongoing'
        type: boolean
        default: false

jobs:
  validate-pr-title:
    runs-on: ${{ inputs.runner }}
    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      PR_LABELS: ${{ inputs.custom_labels }}
      PR_NUMBER: ${{ inputs.pr_number }}
      ERROR_ON_FAILURE: ${{ inputs.error_on_failure }}
      TEST_PHASE_CACHE: ${{ github.workspace }}/test-status
      PCCC_CONFIG_FILE: ${{ github.workspace }}/pccc.toml
    steps:
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{ inputs.action_branch }}
      - name: Install Python Requirements
        run: |
          python -m pip install --upgrade pip
          pip install -r ${{ github.workspace }}/requirements/pip_base.txt
      - name: Get Cached Test Status
        uses: actions/cache@v2
        with:
          path: test-status
          key: test-status-${{ runner.os }}
      - name: Status Check
        run: |
          python scripts/check_PRs.py
        