name: Check Supported Python Versions

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-versions:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4
    - name: Run Python Version Check Script
      run: 
        python scripts/check_supported_py_versions.py
    - name: Commit and Push if Changes
      run: |
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git add supported_py_versions.json
        git commit -m "Update Supported Python Versions" || exit 0  # Exit gracefully if no changes
        git push