on:
  workflow_call:

jobs:
  clear_test_flag:
    runs-on: ubuntu-latest
    # set cached test status to complete
    steps:
      - name: Set test status
        run: |
          echo "complete" > test-status
      - name: Delete Test Tracking Cache
        run: |
          gh extension install actions/gh-actions-cache

          echo "Fetching list of cache key"
          cacheKeys=$(gh actions-cache list -R ${{ github.repository }} -L 100 | cut -f 1 )

          ## Setting this to not fail the workflow while deleting cache keys.
          set +e
          echo "Deleting caches..."
          for cacheKey in $cacheKeys
          do
              gh actions-cache delete $cacheKey -R ${{ github.repository }} --confirm
          done
          echo "Done"
        env:
          GH_TOKEN: ${{ secrets.GH_PAT }}
      - name: Cache test status
        uses: actions/cache@v2
        with:
          path: test-status
          key: test-status-${{ runner.os }}
