name: Propose SemVer Release
on:
  workflow_call:
    inputs:
      branch:
        type: string
        default: dev
      action_branch:
        description: 'The shared action branch to checkout'
        type: string
        default: main
      python_version:
        description: 'The python version to use'
        type: string
        default: "3.8"
      version_file:
        description: 'The file location to read the version from'
        type: string
        default: version.py
      release_type:
        type: string
        description: 'The type of release to make'
        required: true
      changelog_file:
        type: string
        default: CHANGELOG.md
      

jobs:
  bump_version:
    runs-on: ubuntu-latest
    env:
      VERSION_FILE: ${{ github.workspace }}/action/package/${{ inputs.version_file }}
      TARGET_BRANCH: ${{ inputs.release_type == 'patch' && 'testing' || 'stable' }}
      GITHUB_REPOSITORY: ${{ github.repository }}
      RELEASE_TYPE: ${{ inputs.release_type }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}
          path: action/package/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          path: action/github/
          ref: ${{ inputs.action_branch }}
          repository: OpenVoiceOS/.github
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ inputs.python_version }}
      - name: Install Python Dependencies
        run: |
          pip install -r ${{ github.workspace }}/action/github/requirements/pip_base.txt
      - name: Set up Git Authentication
        run: |
          cd ${{ github.workspace }}/action/package/ 
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Create Branch (if necessary)
        run: |
          cd ${{ github.workspace }}/action/package/
          git fetch --unshallow origin ${{ inputs.branch }}
          INITIAL_COMMIT=$(git rev-list --max-parents=0 ${{ inputs.branch }})
          TARGET_BRANCH_EXISTS=$(git ls-remote --heads origin ${{ env.TARGET_BRANCH }} | wc -l)
          if [ "$TARGET_BRANCH_EXISTS" -eq "0" ]; then
            git checkout $INITIAL_COMMIT
            git checkout -b ${{ env.TARGET_BRANCH }}
            git push origin ${{ env.TARGET_BRANCH }} --force
            git checkout ${{ inputs.branch }}
          fi
      - name: Increment Version
        id: version
        run: |
          python action/github/scripts/bump_${{ inputs.release_type }}.py
          VERSION=$(python action/package/setup.py --version)
          echo "VERSION=${VERSION}" >> $GITHUB_ENV
      - name: Push Version Change
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Increment Version to ${{ env.VERSION }}
          repository: action/package/
      - name: Check Latest Release
        run: |
          SINCE_TAG=$(python action/github/scripts/semver_cycle_start.py)
          echo "SINCE_TAG=${SINCE_TAG}" >> $GITHUB_ENV
      - name: Generate Changelog
        id: changelog
        uses: heinrichreimer/github-changelog-generator-action@v2.3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          output: action/package/${{ inputs.changelog_file }}
          futureRelease: ${{ env.VERSION }}
          sinceTag: ${{ env.SINCE_TAG }}
      - name: Push Changelog
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update Changelog
          repository: action/package/
      - name: Checkout Testing Branch
        uses: actions/checkout@v4
        with:
          ref: ${{ env.TARGET_BRANCH }}
          path: action/package/
      - name: Rebase Latest Changes
        run: |
          cd ${{ github.workspace }}/action/package/
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git fetch origin ${{ inputs.branch }}
          git rebase FETCH_HEAD
      - name: Create Pull Request to ${{ env.TARGET_BRANCH }}
        uses: peter-evans/create-pull-request@v5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          path: action/package/
          commit-message: "Propose ${{ inputs.release_type }} release"
          title: "Propose ${{ inputs.release_type }} release"
          body: |
            This pull request proposes a ${{ env.TARGET_BRANCH }} release of the project.
            Please review the changelog and merge if it looks good.
          branch: staging_${{ inputs.release_type }}_release
          base: ${{ env.TARGET_BRANCH }}
          draft: false
          assignees: ${{ github.actor }}
