name: Rebase dev after SemVer bump

# only triggers on pull request closed events
on:
  workflow_call:
    inputs:
      release_type:
        type: string
        description: 'The type of release to make'
        required: true

jobs:
  rebase_dev:
    env:
      SOURCE_BRANCH: ${{ inputs.release_type == 'patch' && 'testing' || 'stable' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "dev"
          fetch-depth: 0
      - name: Set up Git Authentication
        run: |
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
      - name: Rebase testing onto dev
        run: |
          git fetch origin ${{ env.SOURCE_BRANCH }}
          git rebase origin/${{ env.SOURCE_BRANCH }}
      - name: Push changes
        run: |
          git push origin dev