name: Semver release pull request to master
on:
  workflow_call:
    inputs:
      pr_reviewer:
        description: Pull request reviewers, comma-separated list (no spaces)
        required: false
        type: string
      pr_assignee:
        description: Pull request assignees, comma-separated list (no spaces)
        required: false
        type: string
      source_branch:
        description: Branch name to pull from, default is triggered branch
        type: string
        default: "${{ github.ref }}"
      pr_title:
        description: Pull request title
        type: string
      pr_body:
        description: Pull request body
        type: string
      pr_draft:
        description: Draft pull request
        type: boolean
        default: true

jobs:
  pull_changes:
    runs-on: "ubuntu-latest"
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4 
      - name: pull request to master
        uses: repo-sync/pull-request@v2
        # "master" is the `destination_branch` default value
        with:
          source_branch: ${{ inputs.source_branch }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          pr_reviewer: ${{ inputs.pr_reviewer }}
          pr_assignee: ${{ inputs.pr_assignee }}
          pr_draft: ${{ inputs.pr_draft }}
          pr_title: ${{ inputs.pr_title }}
          pr_body: ${{ inputs.pr_body }}