name: Skill Installation Tests
on:
  workflow_call:
    inputs:
      runner:
        description: 'Runner to use'
        type: string
        default: ubuntu-latest
      branch:
        description: 'Branch to use'
        type: string
        default: ${{ github.ref }}
      action_branch:
        description: 'The shared action branch to checkout'
        type: string
        default: main
      python_matrix:
        description: 'Python versions to test against'
        type: string
        default: '["3.8", "3.9", "3.10", "3.11"]'
      system_deps:
        description: 'Additional system dependencies (whitespace delimited) to install'
        required: false
        type: string
      pip_packages:
        description: 'Additional Python packages (whitespace delimited) to install'
        required: false
        type: string
      skill_id:
        description: 'Skill ID to test'
        required: true
        type: string
      skill_location:
        description: 'Relative path to skill'
        type: string
        default: ''
      
jobs:
  test_skill_install:
    runs-on: ${{inputs.runner}}
    timeout-minutes: 5
    strategy:
      matrix:
        python-version: ${{ fromJson(inputs.python_matrix) }}
    steps:
      - name: Checkout Skill Repo
        uses: actions/checkout@v4
        with:
          ref: ${{inputs.branch}}
          path: action/skill/
      - name: Checkout Scripts Repo
        uses: actions/checkout@v4
        with:
          repository: OpenVoiceOS/.github
          ref: ${{inputs.action_branch}}
          path: action/github/
      - name: Set up python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install Common System Dependencies
        run: |
          sudo apt update
          xargs sudo apt install -y < ${{ github.workspace }}/action/github/requirements/sys_deb_common_deps.txt
      - name: Install Custom System Dependencies
        if: ${{ inputs.system_deps != null }}
        run: |
          sudo apt install -y ${{ inputs.system_deps }}
      - name: upgrade pip
        run: |
          pip install --upgrade pip
      - name: Install Common Python Requirements
        run: |
          pip install -r ${{ github.workspace }}/action/github/requirements/pip_skill_tests.txt
      - name: Install Custom Python Requirements
        if: ${{ inputs.pip_packages != null }}
        run: |
          pip install ${{ inputs.pip_packages }}
      - name: Install Python Skill
        run: |
          cd ${{ github.workspace }}/action/skill
          pip install .
      - name: Test Skill Installation
        run: |
          export TEST_SKILL_PATH=${{ github.workspace }}/action/skill/${{inputs.skill_location}}
          export TEST_SKILL_ENTRYPOINT_NAME=${{ inputs.skill_id }}
          pytest ${{ github.workspace }}/action/github/test/test_skill_install.py
